spring.application.name=ejreactiva

spring.datasource.driver-class-name=org.postgresql.Driver
spring.r2dbc.url=r2dbc:postgresql://localhost/ejemreactiva
spring.r2dbc.username=postgres

#spring.datasource.password=20042016
spring.r2dbc.password=12345678
#sql123
server.port=8083